calc_area_1 = 1761.5  # float(input("\nПлоща зовнішніх стін: "))
calc_area_1_1 = 148.6  # float(input("\nПлоща зовнішніх стін нижче відмітки 0.00: "))
calc_area_1_2 = 203.62  # float(input("\nПлоща стін підвалу нижче поверхні землі: "))
calc_area_2 = 758.8  # float(input("\nПлоща перекриття над підвалом, техпідпіллям: "))
calc_area_3_1 = 526.8
calc_area_3_2 = 475.0
calc_area_3_3 = 409.2
calc_area_3_4 = 296.8
calc_area_3 = 1707.8  # float(input("\nПлоща підлоги по грунту: "))
calc_area_4 = 2271.8  # float(input("\nПлоща горищного перекриття: "))
calc_area_5 = 554.7  # float(input("\nПлоща світлопрозорих конструкцій: "))
calc_area_6 = 36.26  # float(input("\nПлоща вхідних дверей: "))
calc_all_initial = calc_area_1 + calc_area_2 + calc_area_3 + calc_area_4 + calc_area_5 + calc_area_6
calc_volume_1 = 15458.1  # float(input("\nОпалювальний об'єм будинку: "))
